### ISSUE TITLE
[Pull request] Add reveiwer doesn't work while in create Pull Request page

### ISSUE THREAD

**Issue by serak88** [atlassian/atlascode#29]
When creating a new PR from VSCode the reviewers field never updates and always shows only the "no options" message.
After creating the PR the "Add reviewer" button opens a dialog that actually works, fetching people from the connected cloud server.

atlascode version 3.0.15

**Comment by sdzh-atlassian** [comment]
Hello there @serak88!

Thanks for reporting this issue to us ;)

It sounds like this might happen on both - but just to confirm, did you observe this while using bitbucket `cloud` or bitbucket `server` - the on-premises one?

If you're not sure - it's totally alright

**Comment by serak88** [comment]
Hello, I'm using bitbucket cloud

**Comment by sdzh-atlassian** [comment]
Thanks! :) Really appreciate the extra info, this helps us understand the incoming issues better

**Comment by TrevinAvery** [comment]
I'm experiencing this same issue using bitbucket cloud. Listing reviewers fails on the create pull request page, but loads just fine after creation and let's me edit the PR.

I don't know if this is at all related, but I found this suspicious log in the extension host output:

```
[error] Error: getaddrinfo ENOTFOUND api.bitbucket.org
    at Function.AxiosError.from (/Users/trevinavery/.vscode/extensions/atlassian.atlascode-3.8.0/build/extension/extension.js:1:1815710)
    at RedirectableRequest.handleRequestError (/Users/trevinavery/.vscode/extensions/atlassian.atlascode-3.8.0/build/extension/extension.js:1:1840950)
    at RedirectableRequest.emit (node:events:530:35)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.b.forEach.w.<computed> (/Users/trevinavery/.vscode/extensions/atlassian.atlascode-3.8.0/build/extension/extension.js:1:406471)
    at ClientRequest.emit (node:events:530:35)
    at ClientRequest.emit (node:domain:489:12)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketErrorListener (node:_http_client:504:5)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/Users/trevinavery/.vscode/extensions/atlassian.atlascode-3.8.0/build/extension/extension.js:1:1854755)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HTTPClient.getUrl (/Users/trevinavery/.vscode/extensions/atlassian.atlascode-3.8.0/build/extension/extension.js:1:2115767)
    at PipelineApiImpl.getPaginatedPipelines (/Users/trevinavery/.vscode/extensions/atlassian.atlascode-3.8.0/build/extension/extension.js:1:2119022)
    at PipelineApiImpl.getSinglepagePipelines (/Users/trevinavery/.vscode/extensions/atlassian.atlascode-3.8.0/build/extension/extension.js:1:2118902)
```

**Comment by BHulovatyi** [comment]
This is no longer relevant. Everything works good.
